version: "3.9"

services:
  database:
    container_name: djangopro_database
    image: postgres:15.3
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=django
      - POSTGRES_USER=diego
    ports:
      - 5434:5432
