# Generated by Django 4.2.1 on 2023-06-11 20:09

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Module = apps.get_model('modules', 'Module')
    for module in Module.objects.all():
        module.slug = slugify(module.title)
        module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_slug'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
