# Generated by Django 4.2.1 on 2023-06-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_populating_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
