# Generated by Django 4.2.2 on 2023-06-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='vimeo_id',
            field=models.CharField(default='1', max_length=36),
        ),
    ]
