name: Django


on:
  pull_request:
    branches:
      - main

jobs:

  build:
    env:
      GITHUB_TOKEN: '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'

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.4
          architecture: x64

      - name: Copying configurations
        run: |
          cp contrib/env-sample .env &&
          cp contrib/flake8 .flake8

      - name: Install dependencies
        run: |
          pip install --upgrade pip &&
          pip install -r requirements.txt


      - name: Run flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'

      - name: Test with pytest
        run: |
          pytest djangopro --cov=djangopro
